name: Build LaTeX and Upload PDF

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.tex"
      - "Makefile"
      - ".github/workflows/*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest-full
      # image: texlive/texlive:TL2023-historic
    steps:
      - uses: actions/checkout@v4
      # - name: Install Dependencies
      #   run: tlmgr install ctex textpos fontawesome5
      - name: Build PDF
        run: make -j$(nproc)
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: out/*.pdf
          compression-level: 0

  prepare-pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Delete All in Current Dir
        run: find . -delete
      - name: Download PDF Artifact
        uses: actions/download-artifact@v4
        with:
          name: cv
          path: .
      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@main
        with:
          FOLDER: .
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy-pages:
    runs-on: ubuntu-latest
    needs: prepare-pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
